name: "Get updated folders"
description: "Get the list of folders that have been updated"

author: Finisterra-io

branding:
  icon: "terminal"
  color: "blue"

inputs:
  base-path:
    description: "Base path to use for the changed files"
    required: true
    default: "finisterra"
  pr-description:
    description: "PR description"
    required: true
    default: "${{ github.event.pull_request.body }}"
outputs:
  folders:
    description: "List of folders that have been updated"
    value: ${{ steps.get-folders.outputs.folders }}
  skip_cicd:
    description: "Whether to skip the cicd or not"
    value: ${{ steps.check-skip.outputs.skip_cicd }}
  AWS_REGION:
    description: "AWS region to use"
    value: ${{ steps.check-skip.outputs.AWS_REGION }}
  AWS_ROLE:
    description: "AWS role to use"
    value: ${{ steps.check-skip.outputs.AWS_ROLE }}
  FOLDER:
    description: "Folder gor generated code"
    value: ${{ steps.check-skip.outputs.FOLDER }}

runs:
  using: "composite"
  steps:
    - name: Check PR description for [skip cicd]
      id: check-skip
      shell: bash
      run: |
        PR_DESCRIPTION="${{ inputs.pr-description }}}"
        PR_DESCRIPTION=$(echo -e "${PR_DESCRIPTION//\#/\\n}")

        if [[ "$PR_DESCRIPTION" == *"[skip cicd]"* ]]; then
          echo "Setting output to skip subsequent jobs."
          echo "skip_cicd=true" >> $GITHUB_OUTPUT

          # Parse AWS_ACCOUNT_ID, AWS_REGION from the PR description.
          FOLDER=$(echo "$PR_DESCRIPTION" | grep -oP 'FOLDER: \K\d+')
          AWS_ACCOUNT_ID=$(echo "$PR_DESCRIPTION" | grep -oP 'AWS_ACCOUNT_ID: \K\d+')
          AWS_REGION=$(echo "$PR_DESCRIPTION" | grep -oP 'AWS_REGION: \K\w+(-\w+)*')

          # Set the parsed values as output variables.
          echo "FOLDER=$FOLDER" >> $GITHUB_OUTPUT
          echo "AWS_REGION=$AWS_REGION" >> $GITHUB_OUTPUT
          echo "AWS_ROLE=arn:aws:iam::$AWS_ACCOUNT_ID:role/gha-cicd" >> $GITHUB_OUTPUT

        else
          echo "Setting output to run subsequent jobs."
          echo "skip_cicd=false" >> $GITHUB_OUTPUT
        fi

    - name: Get changed files
      id: changed-files
      if: ${{ steps.check-skip.outputs.skip_cicd }} != 'true'
      uses: tj-actions/changed-files@v38
      with:
        dir_names: true
        files: finisterra/**/*.{hcl,tf}

    - name: List all changed folders
      id: get-folders
      shell: bash
      run: |
        if [[ "${{ steps.check-skip.outputs.skip_cicd }}" == "true" ]]; then
          folders="[]"
        else
          folders=$(echo ${{ steps.changed-files.outputs.all_modified_files }} | jq -R -s -c '[split(" ")[] | rtrimstr("\n")]')
        fi
        echo "Modified folders: $folders"
        echo "folders=$folders" >> $GITHUB_OUTPUT
