name: "Get updated folders"
description: "Get the list of folders that have been updated"

author: Finisterra-io

branding:
  icon: "terminal"
  color: "blue"

inputs:
  base-path:
    description: "Base path to use for the changed files"
    required: true
    default: "finisterra"
  pr-description:
    description: "PR description"
    required: true
    default: "${{ github.event.pull_request.body }}"
outputs:
  folders:
    description: "List of folders that have been updated"
    value: ${{ steps.get-folders.outputs.folders }}
  skip_cicd:
    description: "Whether to skip the cicd or not"
    value: ${{ steps.check-skip.outputs.skip_cicd }}
  AWS_REGION:
    description: "AWS region to use"
    value: ${{ steps.check-skip.outputs.AWS_REGION }}
  AWS_ROLE:
    description: "AWS role to use"
    value: ${{ steps.check-skip.outputs.AWS_ROLE }}

runs:
  using: "composite"
  steps:
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v38
      with:
        dir_names: true
        files: finisterra/**/*.{hcl,tf}

    - name: List all changed folders
      id: get-folders
      shell: bash
      run: |
        folders_string="${{ steps.changed-files.outputs.all_modified_files }}"
        IFS=' ' read -ra modified_files <<< "$folders_string"

        folders="[]"

        process_folder_for_matrix_data() {
            local folder=$1

            IFS='/' read -ra ADDR <<< "$folder"

            if [ ${#ADDR[@]} -ge 4 ] && [[ "${ADDR[0]}/${ADDR[1]}" == "finisterra/generated" ]]; then
                local folder="${ADDR[0]}/${ADDR[1]}/${ADDR[2]}/${ADDR[3]}/${ADDR[4]}/${ADDR[5]}"
                local aws_account_id="${ADDR[3]}"
                local aws_region="${ADDR[4]}"
                local service_name="${ADDR[5]}"
                if [ "$service_name" == "" ]; then
                    return
                fi
                [ "$aws_region" == "global" ] && aws_region="us-east-1"
                folders=$(echo "$folders" | jq --arg folder "$folder" --arg aws_region "$aws_region" --arg aws_account_id "$aws_account_id" --arg service_name "$service_name" '. + [{folder: $folder, aws_region: $aws_region, aws_account_id: $aws_account_id, service_name: $service_name}]')
            fi
        }

        for folder in "${modified_files[@]}"; do
          process_folder_for_matrix_data "$folder"
        done
        folders=$(echo "$folders" | jq 'unique_by(.folder)')
        folders=$(echo "$folders" | jq -c .)
        echo "Modified folders: $folders"
        echo "folders=$folders" >> $GITHUB_OUTPUT
